# Simple deployment used to deploy and manage the app in nigelpoulton/getting-started-k8s:1.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-basic-deploy
  labels:
    name: sample-basic-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      name: sample-basic-app
  template:
    metadata:
      labels:
        name: sample-basic-app
    spec: 
      terminationGracePeriodSeconds: 1
      containers:
      - name: sample-basic-ctr
        image: salimsaidhemed1989/sample-basic:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000